### ISSUE TITLE
Hardcoded value

### ISSUE THREAD

**Issue by daniel-unyi-42** [kharitz/aligned_spectral_embedding#1]
The value 5 is hardcoded here, I believe it should be 'krot' instead:

https://github.com/kharitz/aligned_spectral_embedding/blob/a93b4e31ede3b93341fe9ab1bccfb550c3a154c5/utils/SpectralMatching/transformation.py#L66

**Comment by kharitz** [comment]
You are rite. I am uploading the updated version of spectral alignment in python

**Comment by daniel-unyi-42** [comment]
I also found a possible mistake in 
https://github.com/kharitz/aligned_spectral_embedding/blob/a93b4e31ede3b93341fe9ab1bccfb550c3a154c5/utils/SpectralMatching/flip_eigen.py#L13
Shouldn't the iteration go from 0 to the number of eigenvectors?

(I'm trying to align the Mindboggle cortical meshes and I get a low value for some of the meshes, I suspect this might be the problem)

**Comment by kharitz** [comment]
Yes definitely. By the end of the week, I will upload the python version
(using the Pytorch library and GPU capabilities)

Karthik

**Comment by daniel-unyi-42** [comment]
Thank you!

**Comment by daniel-unyi-42** [comment]
Hope you don't mind it, just wanted to remind you that I'm waiting for the updated version :)

**Comment by kharitz** [comment]
Yes. I am working on it. Sorry for the delay and inconvenience.

Karthik

**Comment by kharitz** [comment]
Hi,

I've included this link for you for the updated version. I had to push it
early so that you could use it.

https://github.com/kharitz/brain-surface-spectral-alignment.git

Please let me know if you find any issues, and I will fix them as soon as
possible.

I appreciate your patience,
Karthik

**Comment by daniel-unyi-42** [comment]
Thank you, I highly appreciate it! Last week was quite busy but this week I'm going to test it!
